version: '3.1'

services:
  db1:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'primary-db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3306"
    volumes:
      - my-db1:/var/lib/mysql
    expose:
      - "3307"
  db2:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'secondary-db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3308:3306"
    volumes:
      - my-db2:/var/lib/mysql
    expose:
      - "3308"


volumes:
  my-db1:
  my-db2: